language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
after_success:
- ./gradlew cobertura coveralls --stacktrace
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
  - secure: enqw1gF575pn9fNNUunkfRre0mRKkwXfJRb/jHh7acIrjF6mO1w+yETv777C3U2/oLaIFLLocxNQdbEN5pBz85xGnrXFekeKzJHIDgwr58W1SlWMm9+dxb4FOvvtjBNgoPQWrNZn9WA6aL70DgodfD/e3RXpSlQDMeStliGkr2CeUnvetgrRvhwdgmdRM9Gbe79r2iMePprqiqc6sGPTkTM4ZMkb361MzIEkylvwaAqQAANXJS+4GsItpnPNAfynz8Ho2facNBtMeTYNp/OwaaISmS3UsmlwEYzh/lBgHvakMo5sP/CE1Nj4wfwCJSni9FXcAXp3Dk7EaV+huEKGkAE1xfYpNGke1gEE4vay7+P5GwvjiwcNxvhmepyYVevbdatonmiZ5TIH8FAQUnBBi9Yk8mMUFd/u4ui14qzs0jULvTyTT3MhrdUB9rn1qrP562QFmV8Yxsgvr4dbWiuVBVUNu/7fbl6pgQp4RoSt35nfMNP0S6Xy3xK10Ok1nnsMlXGzMbB+PZXZbuwUIFMF0y+HLwkLtquRJCUoh5H9nwWpOzQXV4fQF+gPXmybTsM6UpiluUSi3ujC+O3V8ifR0EV6fzRuq/xfNGH4ydWM/fidxbpQ+J4bsomjoa4nbCTaSvjRqYK5A3G22FHgM8cXlrJC1YY1QEYSL2R6Wr3I9gM=
  - secure: XUeegCmgt3nma/Tzb+0DPkXbXTCPmj6lsu4O6tXxSBD4yLGj4j2jrBtVbs+zm8gR0nrEzrZ8dlbhC9qD9Osm+RYA4DB+vWiLJ4EZHMuoLTUb95CXS/zR8HqSfCulG8cd5Qp9fzSWHiQhaBW73xoXtqWWjJUrKxo9qggUB14aB8IwisPkpCGPjg/pJFU3GrPulGE+IDAKEE8T0xpeLyAavC+/m8Z4bfK0PWFanXXHD5uDVXD5GNdwE9iXBPh0Njm9l7n33MrYhxPLqlMPaeP6Hpptt6srd3+jUVWJwLkUf5XyUtotv43U1zKogpQLXv4dA7oSZ0p327Sdceze5kv1n7X03AXc838h6xzXMgqNEHwfwK0siMm/5n6YTI/5wOX2wU51lvM4s3NSc+lzaNZri60n+F3R1qE82HXkkbVPm2sCg8Tl6PCsAYmzVDguqO2hrgjzMoFPNlGktlWzY2OxR+BZ9uO/toKhJv0O8CVLqbNb9mv2ETlcXEAslursw3NjrXv9oaJualvbA2Ln4tw2tve4GvVm2zNHg0XRQG7Zxl4GIIk8GNJLW5r36DM9QoLd17zmEgVmmM0ZP4EyX0Q2uYHAuk06L3Qr1JF/CL9UTZDbUHJtxdRn5MM9S2HcUZ+VJ1Rn/JOKJfS7xl0AfhEHZ3tC+xwatMSvU0LGai4fygg=
